development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: mertersitesi@gmail.com	
  :password: merter12345
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: mertersitesi@gmail.com
  :password: merter12345
  :enable_starttls_auto: true
